### ISSUE TITLE
Double opt-in and approve by admin

### ISSUE THREAD

**Issue by t-book** [huychau/drf-registration#2]
Dear @huychau,

thanks for this great module. Hope this is the correct place to ask. I'm in the need of the following workflow:

1. A user registers
2. an email is sent to validate the email address (`'USER_ACTIVATE_TOKEN_ENABLED': True,`) 
3. an admin gets an email with a link to approve the signup (`is_active=True`)

So far my idea is ...

... to add a new field to my user model like `email_is_valid` which instead of`is_active` is set to `True|False` (step 2). 
... Further to set up a signal which sends an E-Mail to an Admin afterward who would finally set `is_active=True` (step 3).

My question is, do I reinvent the wheel? Or is there already something onboard?

**Comment by huychau** [comment]
Hi @t-book thanks for your nice question. 
Currently, the email confirmed field is `is_active` by default. You can change any field like `email_is_valid` or `is_email_confirmed`, etc follow [this guilde](https://drf-registration.readthedocs.io/en/latest/settings/user.html?highlight=USER_VERIFY_FIELD#USER_VERIFY_FIELD).

Admin approve feature is not supported in this package yet. I think the flow with both **user confirm** their email and **admin approval** is not a common case. 

Let me know if you need more update/feature, thanks.
