### ISSUE TITLE
I want to set the user active for the first 48 hours upon registration

### ISSUE THREAD

**Issue by devspectre** [huychau/drf-registration#9]
Hi!

Thank you for your great work.
This really saves a lot of time and effort.

I want to set the user active for the first 48 hours upon registration.
And after 48 hours, set the accounts inactive if they haven't verified email yet.
How can I do this with drf-registration?
I don't see any option on default settings for those settings.

Thanks in advance.

**Comment by huychau** [comment]
Hi @devspectre, thanks for your great question. DRF Registration does not support Celery, tasks, jobs for now. So if you want, you can create the cron job by yourself to check the user status.

Let me know if you want to support more.

**Comment by devspectre** [comment]
Hi @huychau 

Yes, I got it.
Then after 48 hours, how can I notice that the user hasn't verified the email yet from `User` model?
`is_active` flag does that?
Which field are you using to mark that?

**Comment by huychau** [comment]
@devspectre Thanks for your great question, but this package does not support your request now. I will check and consider to add in the future if any, thanks.
